# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(blank=True, max_length=255)),
                ('student_number', models.CharField(blank=True, max_length=255)),
                ('employee_first_name', models.CharField(blank=True, max_length=255)),
                ('employee_last_name', models.CharField(blank=True, max_length=255)),
                ('employee_email', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course_number', models.CharField(blank=True, max_length=255)),
                ('course_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
