# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safetyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_last_name',
            new_name='last_name',
        ),
    ]
