# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safetyapp', '0006_employee_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hazard_code', models.CharField(blank=True, max_length=255)),
                ('safety_courses', models.ManyToManyField(blank=True, to='safetyapp.SafetyCourse')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project_number', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('t00016', models.BooleanField(default=False, verbose_name='Take photographs')),
                ('t00030', models.BooleanField(default=False, verbose_name='Use a portable or fixed ladder')),
                ('t00001', models.BooleanField(default=False, verbose_name='Operate a circuit breaker')),
                ('t00021', models.BooleanField(default=False, verbose_name='Open an electrical box/cabinet/panel (480V or less)')),
                ('t00022', models.BooleanField(default=False, verbose_name="Open a facility's main electrical panel board (480V or less)")),
                ('t00023', models.BooleanField(default=False, verbose_name='Measure voltage or test de-energization (480V or less)')),
                ('t00024', models.BooleanField(default=False, verbose_name='Work with de-energized electrical equipment (480V or less)')),
                ('t00025', models.BooleanField(default=False, verbose_name='Install or uninstall clamp-on CT (480V or less)')),
                ('t00011', models.BooleanField(default=False, verbose_name='Work on electrical systems with multiple power sources')),
                ('t00008', models.BooleanField(default=False, verbose_name='Internal inspection of light fixture')),
                ('t00009', models.BooleanField(default=False, verbose_name='External inspection of light fixture')),
                ('t00013', models.BooleanField(default=False, verbose_name='Direct install: light bulbs and non-wired loggers')),
                ('t00014', models.BooleanField(default=False, verbose_name='Direct install: plumbing')),
                ('t00015', models.BooleanField(default=False, verbose_name='Direct install: mizers')),
                ('f00002', models.BooleanField(default=False, verbose_name='General industrial')),
                ('f00003', models.BooleanField(default=False, verbose_name='General residential')),
                ('f00004', models.BooleanField(default=False, verbose_name='General commercial')),
                ('f00005', models.BooleanField(default=False, verbose_name='Refinery')),
                ('f00006', models.BooleanField(default=False, verbose_name='Warehouse')),
                ('f00007', models.BooleanField(default=False, verbose_name='Construction site')),
                ('f00008', models.BooleanField(default=False, verbose_name='Outdoor work')),
                ('s00008', models.BooleanField(default=False, verbose_name='Electrical - Energized Work')),
                ('s00002', models.BooleanField(default=False, verbose_name='Rooftops')),
                ('s00001', models.BooleanField(default=False, verbose_name='Air handler units')),
                ('s00004', models.BooleanField(default=False, verbose_name='Refrigeration compressor rooms')),
                ('s00007', models.BooleanField(default=False, verbose_name='Mechanical rooms')),
                ('s00003', models.BooleanField(default=False, verbose_name='Combustion gases')),
                ('s00005', models.BooleanField(default=False, verbose_name='Compressed air')),
                ('s00006', models.BooleanField(default=False, verbose_name='Steam systems')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='business_unit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='business_unit_group',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='business_unit_practice',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='engineering_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='field_equip_coord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='field_safety_coord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_project_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_safety_dashboard_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_temp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_safety_coord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='site_sustainability_coord',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(blank=True, to='safetyapp.Employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='hazards',
            field=models.ManyToManyField(blank=True, to='safetyapp.Hazard'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to='safetyapp.Employee'),
        ),
    ]
