# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safetyapp', '0007_auto_20170301_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='hazard_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
