# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safetyapp', '0008_hazard_hazard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='business_unit',
            field=models.CharField(blank=True, choices=[('Corporate', 'Corporate'), ('Energy & Chem Advisory', 'Energy & Chem Advisory'), ('Markets', 'Markets'), ('Software', 'Software'), ('Utility Services', 'Utility Services')], max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='business_unit_group',
            field=models.CharField(blank=True, choices=[('Corporate', 'Corporate'), ('E&CA: Commercial', 'E&CA: Commercial'), ('E&CA: Government', 'E&CA: Government'), ('E&CA: Nexant Thinking', 'E&CA: Nexant Thinking'), ('Markets', 'Markets'), ('Software: Grid Mgmt', 'Software: Grid Mgmt'), ('Software: iEnergy', 'Software: iEnergy'), ('Software: Revenue Manager', 'Software: Revenue Manager'), ('UTS: Administration', 'UTS: Administration'), ('UTS: Energy Eff Delivery', 'UTS: Energy Eff Delivery'), ('UTS: Strategy & Planning', 'UTS: Strategy & Planning')], max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='business_unit_practice',
            field=models.CharField(blank=True, choices=[('Corp: Executive', 'Corp: Executive'), ('Corp: Finance & Acct', 'Corp: Finance & Acct'), ('Corp: Human Resources', 'Corp: Human Resources'), ('Corp: Info Technology', 'Corp: Info Technology'), ('Corp: Legal & Contracts', 'Corp: Legal & Contracts'), ('Corp: Marketing', 'Corp: Marketing'), ('Corp: Operations', 'Corp: Operations'), ('Corp: Sales', 'Corp: Sales'), ('E&CA: Commercial-Americas', 'E&CA: Commercial-Americas'), ("E&CA: Commercial-Intern'l", "E&CA: Commercial-Intern'l"), ('E&CA: Government', 'E&CA: Government'), ('E&CA: Nexant Thinking', 'E&CA: Nexant Thinking'), ('Markets', 'Markets'), ('Software: Grid Mgmt-DM360', 'Software: Grid Mgmt-DM360'), ('Software: Grid Mgmt-Prod', 'Software: Grid Mgmt-Prod'), ('Software: iEnergy', 'Software: iEnergy'), ('Software: Revenue Manager', 'Software: Revenue Manager'), ('UTS: Admin-Business Dev', 'UTS: Admin-Business Dev'), ('UTS: Admin-Business Ops', 'UTS: Admin-Business Ops'), ('UTS: Admin-Executive', 'UTS: Admin-Executive'), ('UTS: EED-Business Mgmt', 'UTS: EED-Business Mgmt'), ('UTS: EED-Business Proc', 'UTS: EED-Business Proc'), ('UTS: EED-Engineering', 'UTS: EED-Engineering'), ('UTS: EED-I&OD', 'UTS: EED-I&OD'), ('UTS: EED-ICS', 'UTS: EED-ICS'), ('UTS: EED-Marketing', 'UTS: EED-Marketing'), ('UTS: EED-TradeAlly', 'UTS: EED-TradeAlly'), ('UTS: S&P-FSC', 'UTS: S&P-FSC'), ('UTS: S&P-Grid Consulting', 'UTS: S&P-Grid Consulting'), ('UTS: S&P-Planning & Eval', 'UTS: S&P-Planning & Eval')], max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, choices=[('Burlington, MA', 'Burlington, MA'), ('Canada', 'Canada'), ('Cary, NC', 'Cary, NC'), ('Chandler, AZ', 'Chandler, AZ'), ('Des Moines, IA', 'Des Moines, IA'), ('Hinsdale, IL', 'Hinsdale, IL'), ('India', 'India'), ('Jacksonville, FL', 'Jacksonville, FL'), ('Louisville, CO', 'Louisville, CO'), ('Madison, WI', 'Madison, WI'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('Salt Lake City, UT', 'Salt Lake City, UT'), ('San Francisco, CA', 'San Francisco, CA'), ('San Mateo, CA', 'San Mateo, CA'), ('Telecommuter - Argentina', 'Telecommuter - Argentina'), ('Telecommuter - Arizona', 'Telecommuter - Arizona'), ('Telecommuter - California', 'Telecommuter - California'), ('Telecommuter - Canada', 'Telecommuter - Canada'), ('Telecommuter - Colorado', 'Telecommuter - Colorado'), ('Telecommuter - Georgia', 'Telecommuter - Georgia'), ('Telecommuter - Idaho', 'Telecommuter - Idaho'), ('Telecommuter - Illinois', 'Telecommuter - Illinois'), ('Telecommuter - India', 'Telecommuter - India'), ('Telecommuter - Indiana', 'Telecommuter - Indiana'), ('Telecommuter - Kentucky', 'Telecommuter - Kentucky'), ('Telecommuter - Latvia', 'Telecommuter - Latvia'), ('Telecommuter - Maine', 'Telecommuter - Maine'), ('Telecommuter - Massachusetts', 'Telecommuter - Massachusetts'), ('Telecommuter - Michigan', 'Telecommuter - Michigan'), ('Telecommuter - Mississippi', 'Telecommuter - Mississippi'), ('Telecommuter - Nevada', 'Telecommuter - Nevada'), ('Telecommuter - New Mexico', 'Telecommuter - New Mexico'), ('Telecommuter - New York', 'Telecommuter - New York'), ('Telecommuter - North Carolina', 'Telecommuter - North Carolina'), ('Telecommuter - Oregon', 'Telecommuter - Oregon'), ('Telecommuter - Pennsylvania', 'Telecommuter - Pennsylvania'), ('Telecommuter - South Carolina', 'Telecommuter - South Carolina'), ('Telecommuter - Tennessee', 'Telecommuter - Tennessee'), ('Telecommuter - Texas', 'Telecommuter - Texas'), ('Telecommuter - USAID Djibouti/Inanda', 'Telecommuter - USAID Djibouti/Inanda'), ('Telecommuter - USAID Ethiopia', 'Telecommuter - USAID Ethiopia'), ('Telecommuter - USAID Ghana', 'Telecommuter - USAID Ghana'), ('Telecommuter - USAID Kenya', 'Telecommuter - USAID Kenya'), ('Telecommuter - USAID Nigeria', 'Telecommuter - USAID Nigeria'), ('Telecommuter - USAID Pretoria', 'Telecommuter - USAID Pretoria'), ('Telecommuter - Utah', 'Telecommuter - Utah'), ('Telecommuter - Vietnam', 'Telecommuter - Vietnam'), ('Telecommuter - Virginia', 'Telecommuter - Virginia'), ('Telecommuter - Washington ', 'Telecommuter - Washington '), ('Telecommuter - Wisconsin', 'Telecommuter - Wisconsin'), ('Telecommuter - Wyoming', 'Telecommuter - Wyoming'), ('Washington, DC', 'Washington, DC'), ('White Plains, NY', 'White Plains, NY')], max_length=255),
        ),
    ]
