# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safetyapp', '0009_auto_20170301_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255),
        ),
    ]
