# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safetyapp', '0010_auto_20170301_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetycourse',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
