# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-03 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnnfgiapp', '0002_auto_20170402_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgi',
            name='week_day',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
